 pkgs: [
    pkgs.ccls
    pkgs.cgdb
    pkgs.codex
    pkgs.delta
    pkgs.dotbot
    pkgs.duf
    pkgs.fd
    pkgs.fzf
    pkgs.gdb
    pkgs.git
    pkgs.jq
    pkgs.lazygit
    pkgs.mycli
    pkgs.neovim
    pkgs.nvimpager
    pkgs.ripgrep
    pkgs.starship
    pkgs.tailspin
    pkgs.tmux
    pkgs.yazi
    pkgs.zoxide
    pkgs.age
    pkgs.bat
    pkgs.btop
    pkgs.git-filter-repo
    pkgs.gitleaks
    pkgs.lazydocker
    pkgs.leetgo
    pkgs.mise
    pkgs.sops
    pkgs.tmuxp
  ]
